version: '3.8'
services:
  cassandra:
    image: 'cassandra:3.11'
    container_name: cassandra
    hostname: cassandra
    environment:
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=1G
      - CASSANDRA_CLUSTER_NAME=thp
    volumes:
      - './cassandra/data:/var/lib/cassandra/data'
  thehive:
    image: 'thehiveproject/thehive4:latest'
    container_name: thehive4
    restart: unless-stopped
    depends_on:
      - cassandra
    ports:
      - '0.0.0.0:9000:9000'
    volumes:
      - type: bind
        source: './thehive/application.conf'
        target: /etc/thehive/application.conf
        read_only: true
      - type: bind
        source: './thehive/data'
        target: /opt/thp/thehive/data
        read_only: false
      - type: bind
        source: './thehive/index'
        target: /opt/thp/thehive/index
        read_only: false
    command: '--no-config --no-config-secret'
